name: intrinsics-imaging
channels:
  - conda-forge
dependencies:
  - jupyter
  - matplotlib-base
  - numpy
  - pandas
  - pillow
  - python=3.10
  - tomli
  - pytorch
  - scikit-image
  - scipy
  - torchvision
  - tqdm
